### ISSUE TITLE
Einflüsse durch Waffenaufsätze

### ISSUE THREAD

**Issue by mordl** [shukari/TBMod#10]
Das ist ein Thema, dass mir schon lange durch den Kopf geht.
Jetzt kann ich ja mal nachfragen^^

1. Sind bei unserem Recoilsystem die Handgriffe, die nicht fürs Auflegen gedacht sind (Grip Pod im nicht ausgefahrenen Zustand) noch effektiv?

2. Beeinflussen der Muzzlebraker und der Flash Hider die Stabilität der Waffe?
Soweit ich mich nicht irre ist der MB für Einzelschuss gedacht und der FH für Dauerfeuer.
Aber tun sie das auch in Arma? 

3. Haben die unterschiedlichen Versionen der Waffen (z.B. MK18 und MK18/SOPMOD Stock)
Unterschiede in ihren Werten? Bei der normalen Arsenalauswahl ist nichts erkennbar.

Würde mich freuen, wenn du mal die Zahlen anschauen kannst. Ich kann es nicht.
Und bei Tests in VR bemerke ich nichts.

Gruß mordl

**Comment by shukari** [comment]
Unser Recoilsystem ist wenn es um deine Punkte geht "einfach" ^^
[Hier ist der Code](https://github.com/shukari/TBMod/blob/master/addons/TBMod_main/functions/fn_recoilSystem.sqf), derzeit wird nur geschaut ob du ein MG hast, dann ist der Recoil größer, ob du passiv abstützt, ob du aktiv abstützt und wie deine Ausdauer (kleiner = mehr Rückstoß) ist.
Das Recoilsystem derzeit soll vorbereitete Aktionen stärken und sinnloses reinlaufen bestrafen, aber deine Punkte sind richtig gut un unbedingt zu implementieren.

Eigl. wollte ich das Wackeln damals anpassen, das ging aber wegen ACE nicht, jetzt schon, deswegen Recoil angepasst.

**Comment by shukari** [comment]
Zu dem Recoil der Waffen muss ich erst nachforschen welche Werte das sind.

**Comment by shukari** [comment]
Ergebnisse vom rum experimentieren:
- Waffen haben Recoils diese sind in CfgRecoils definiert, ACE verringert diese
- RHS benutzt für fast alle M4s und M16 den Rückstoß der Vanilla MXM ^^
- der Feuermodus hat auch einen Recoil konnte aber bei meinen Tests keinen Unterschied feststellen
- Attachements haben KEINEN Einfluss, gerade MB und Schallis haben keine möglichkeit dafür, ABER die Grips könnten einfluss haben, da sie intern neue Waffen sind... ohne Gripp ist eine andere Waffe als mit einem... dadurch kann man den Rückstoß für Grippwaffen per Config verändern
- generell könnte man allgemein den Rückstoß anpassen, da alle RHS waffen vanilla Recoil benutzen
- würde das alles per Skript abdecken und nicht per Config, also ist es Möglich Griffe und MB einzubeziehen

**Comment by shukari** [comment]
Neu in 3bd8f12f0b3e8a70db85430a4a170e900cdce7bd:
- Schalldämpfer erhitzen schneller die Waffe etwa doppelt so viel pro Schuss
- Schalldämpfer und Griffe senken seperat das Recoil
- die beiden Muzzlebraker/FlashHider setzen den Recoil stärker runter als ein Schalli aber nur im Einzelfeuer (MB/FH machen keine zusätzliche Hitze)
- kleinere Optimierungen am RecoilSystem
