### ISSUE TITLE
Arsenal Waffenwechsel

### ISSUE THREAD

**Issue by mordl** [shukari/TBMod#24]
Wenn man im Arsenal die Waffe wechselt werden alle Magazine aus dem inventar entfernt
und in der Waffe taucht ein nicht gelistetes Stanag Magazin auf.

**Comment by shukari** [comment]
@mordl 
So funktiniert das Arsenal, wenn du die Waffe wechselt ist er so nett und löscht die vom alten, das du die nicht entfernen musst.
Mit dem STANAG ist das so das das erscheint, weil die Waffe in der Config als Standard Mag das Stanag gesetzt hat und so siehst du alle Whitelisted Mags plus das was gerade drin ist.

Die erste Sache, werde ich nicht verändern, ist zu 90% nützlich, aber das zweite werde ich angehen ;D
