### ISSUE TITLE
Neue Standardausrüstungen

### ISSUE THREAD

**Issue by mordl** [shukari/TBMod#25]
Würde gerne ein paar neue Preset Layouts für manche Klassen erstellen. 
Ich finde die bisherigen veraltet. 

Gruß mordl

**Comment by shukari** [comment]
@mordl 
Einfach machen, die sind jetzt 1,5 Jahre alt.

HowTo:
- Editor gehen
- eine Einheit hinstellen
- unter LEER/Requisiten (gelb) unter TB - MainStuff > Arsenal das gewünschte Arsenal auswählen
- alles ausrüsten unten auf Export
- das ganze dann hier rein kopieren mit der rolle oder alles in eine Textdatei und mir hochladen

Beachten:
- keine Spezialausrüstung (NachtStuff usw)
- Standard Loadout soll Grundlage sein, der Rest soll oben drauf reingepackt werden, also nicht alles voll packen
- simpelste Standard Sachen
- ggf bei USA auf OCP wechseln wird häufiger benutzt UCP wird selten benutzt, denke ich

**Comment by mordl** [comment]
Achtung:
Bei den Layouts werde ich keine Waffen einfügen. Ich teste die Layouts mit dem schwersten Sturmgewehr, um nicht über 35kg zu kommen. Danach entferne ich sie wieder. Die Magazine würden beim Wechseln der Waffe sowieso zurückgesetzt werden bzw. gar nicht passen. Mein Ziel ist es Anfänger einer neuen Klasse ein Layout zu geben, wo sie nur noch ihre Waffen zusammenbauen müssen und vielleicht ein paar individuelle Vorlieben ändern können.

**Comment by mordl** [comment]
Truppführer:
[[],[],[],["rhs_uniform_cu_ocp",[["ACE_morphine",5],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",5]]],["rhsusf_spcs_ocp_squadleader",[["ACE_HuntIR_M203",5,1],["rhs_mag_M441_HE",5,1],["rhs_mag_m67",2,1],["SmokeShellBlue",1,1],["rhs_mag_mk3a2",1,1]]],["TFAR_rt1523g_big_rhs",[["ACE_HuntIR_monitor",1],["SmokeShell",4,1]]],"rhsusf_ach_helmet_ocp","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]

**Comment by mordl** [comment]
Grenadier:
[[],[],[],["rhs_uniform_cu_ocp",[["ACE_morphine",5],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",5]]],["rhsusf_spcs_ocp_squadleader",[["ACE_HuntIR_M203",5,1],["rhs_mag_M441_HE",5,1],["rhs_mag_m67",2,1],["SmokeShellBlue",1,1],["rhs_mag_mk3a2",1,1]]],["TFAR_rt1523g_big_rhs",[["ACE_HuntIR_monitor",1],["SmokeShell",4,1]]],"rhsusf_ach_helmet_ocp","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]

**Comment by mordl** [comment]
Zu dem Sanimaterial:
Ich benutze schon eine ganze Weile die Wundverbände. Seit kurzen auch in Kombination mit Quicks.
Quickclots sind besonders effektiv, wenn das Team leicht angesplittert wurde. Dadurch können kleine Schittwunden gesichert werden, ohne dass ein Sani alle gleich Nähen muss.
Wundverbände geben Frontsoldaten die Möglichkeit auch große Kopf- u. Torsoverletzungen schnell zu behandeln, ohne das sie beim Aufstehen gleich wieder abfällt. Zudem wird dadurch verhindert, dass der Sani die Bandagen des Soldaten verbraucht. 5 Morphium Standard. 4 Torniquets, falls der Sani vergisst sie zurückzugeben, oder ein Totalschaden abgedichtet gehört.

**Comment by mordl** [comment]
Unterstützungsschütze:
[[],[],[],["rhs_uniform_cu_ocp",[["ACE_morphine",5],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_tourniquet",4],["ACE_fieldDressing",20]]],["rhsusf_spcs_ocp_machinegunner",[["ACE_EntrenchingTool",1],["SmokeShell",5,1],["SmokeShellBlue",1,1]]],["rhsusf_assault_eagleaiii_ocp",[]],"rhsusf_ach_helmet_ocp","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]

**Comment by mordl** [comment]
Sprengmeister:
[[],[],[],["rhs_uniform_cu_ocp",[["ACE_morphine",5],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",5]]],["rhsusf_spcs_ocp",[["ACE_M26_Clacker",1],["rhs_mag_m67",2,1],["DemoCharge_Remote_Mag",4,1],["rhs_mag_mk3a2",1,1],["SmokeShellBlue",1,1]]],["rhsusf_assault_eagleaiii_ocp",[["SmokeShell",4,1]]],"rhsusf_ach_helmet_ocp","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]

**Comment by mordl** [comment]
AT-Schütze:
[[],[],[],["rhs_uniform_cu_ocp",[["ACE_morphine",5],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",5]]],["rhsusf_spcs_ocp_saw",[["SmokeShell",4,1],["SmokeShellBlue",1,1]]],["B_Carryall_cbr",[]],"rhsusf_ach_helmet_ocp","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]

**Comment by mordl** [comment]
Munitionsträger:
[[],[],[],["rhs_uniform_cu_ocp",[["ACE_morphine",5],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",5]]],["rhsusf_spcs_ocp_machinegunner",[["rhs_mag_m67",2,1],["SmokeShellBlue",1,1],["SmokeShell",4,1],["rhs_mag_mk3a2",1,1]]],["B_Carryall_cbr",[["ACE_EntrenchingTool",1]]],"rhsusf_ach_helmet_ocp","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]

**Comment by mordl** [comment]
Gruppenaufklärer:
[[],[],[],["rhs_uniform_cu_ocp",[["ACE_morphine",5],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",5]]],["rhsusf_spcs_ocp",[["rhsusf_acc_SR25S_d",1],["ACE_RangeCard",1],["rhs_mag_m67",2,1],["SmokeShellBlue",1,1],["rhs_mag_mk3a2",1,1]]],["rhsusf_assault_eagleaiii_ocp",[["ACE_EntrenchingTool",1],["SmokeShell",4,1]]],"rhsusf_ach_helmet_ocp","",["ACE_Yardage450","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]

**Comment by mordl** [comment]
Pilot:
[[],[],[],["U_B_PilotCoveralls",[["ACE_morphine",5],["ACE_MapTools",1],["ACE_CableTie",1],["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",5]]],[],[],"","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]

**Comment by mordl** [comment]
Sniper und Spotter lasse aus. Werden nur selten benutzt und die Leute, die diese Rollen spielen, "sollten" genug Erfahrung haben sich selber etwas zusammenzustellen.

**Comment by mordl** [comment]
DrohnenOP:
[[],[],[],["rhs_uniform_cu_ocp",[["ACE_morphine",5],["ACE_CableTie",1],["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_quikclot",5],["ACE_MapTools",1]]],["rhsusf_spcs_ocp_rifleman",[["ACE_EntrenchingTool",1],["rhs_mag_m67",2,1],["rhs_mag_mk3a2",1,1],["SmokeShell",4,1],["SmokeShellBlue",1,1]]],["B_UAV_01_backpack_F",[]],"rhsusf_ach_helmet_ocp","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]

**Comment by mordl** [comment]
Arzt: Außer Helm/Uniform gleiches Layout von Kampfsanitäter. 
[[],[],[],["rhs_uniform_g3_tan",[["ACE_tourniquet",4],["ACE_morphine",5],["ACE_CableTie",1],["ACE_MapTools",1],["ACE_fieldDressing",10],["ACE_quikclot",5]]],["rhsusf_spcs_ocp_medic",[["ACE_surgicalKit",1],["ACE_personalAidKit",3],["ACE_tourniquet",4],["ACE_elasticBandage",50],["ACE_epinephrine",10]]],["B_Kitbag_cbr",[["ACE_morphine",20],["ACE_bloodIV",10],["SmokeShell",6,1],["SmokeShellBlue",1,1]]],"rhsusf_cvc_alt_helmet","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]

**Comment by mordl** [comment]
Schütze:
[[],[],[],["rhs_uniform_cu_ocp",[["ACE_MapTools",1],["ACE_CableTie",1],["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_morphine",10],["ACE_quikclot",5]]],["rhsusf_spcs_ocp",[["ACE_fieldDressing",15],["ACE_morphine",5],["ACE_quikclot",5],["rhs_mag_mk3a2",3,1],["rhs_mag_m67",3,1],["SmokeShellBlue",1,1]]],["rhsusf_assault_eagleaiii_ocp",[["ACE_EntrenchingTool",1],["SmokeShell",6,1]]],"rhsusf_ach_helmet_ocp","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]

**Comment by mordl** [comment]
Pionier:
[[],[],[],["rhs_uniform_cu_ocp",[["ACE_MapTools",1],["ACE_CableTie",1],["ACE_tourniquet",4],["ACE_fieldDressing",15],["ACE_morphine",10],["ACE_quikclot",5]]],["rhsusf_spcs_ocp",[["ACE_fieldDressing",15],["ACE_morphine",5],["ACE_quikclot",5],["rhs_mag_mk3a2",1,1],["rhs_mag_m67",2,1],["SmokeShellBlue",1,1]]],["rhsusf_assault_eagleaiii_ocp",[["ACE_EntrenchingTool",1],["SmokeShell",4,1]]],"rhsusf_ach_helmet_ocp","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]
