### ISSUE TITLE
Grenadier/Truppführer: M320 GLM

### ISSUE THREAD

**Issue by mordl** [shukari/TBMod#26]
Einleitung: Obwohl es für den Grenadier/Truppführer keine Gewehre ohne ULG gibt, befindet sich der sekundäre Granatenwerfer M320 GLM noch im Arsenal.

Meine Idee:
Dem Grenadier/Truppführer wieder Zugang zu Gewehren ohne ULG geben. 

Pro:
Dadurch kann ein Grenadier z.B. für Stadtkämpfe einen Griff an seine Waffe befestigen für erhöhte Stabilität. Zudem kann er auch schneller zwischen Dauerfeuer und Einzelschuss wechseln, da der ULG nicht mehr unter der Option ist.

Truppführer bekommen dadurch Zugriff auf den Harris Bipod und können z.B. in einem Unterstützertrupp mit einer M16 besser aus dem Rückraum wirken, ohne Zugriff auf eigene Hunter IR´s zu verlieren.

Kontra:
M320 GLM koordinierter einsetzen, da das Wechseln länger dauert als mit ULG.
Keine Sekundärwaffe. 

Gruß mordl

**Comment by shukari** [comment]
Hauptgrund warum es keine ohne UGL gibt, weil das Arsenal für diese Rolle dann 500 Waffen hat und ich gerade in letzter Zeit, versucht hatte etwas aufzuräumen... ;D
Aber können wir drüber nachdenken

**Comment by mordl** [comment]
Können ja dann nur jeweils eine Version von M16(Distanz) und Mk18(Stadt) für den Anfang einfügen und schauen, ob die Nachfrage für mehr kommt.
