### ISSUE TITLE
Modus für VIP

### ISSUE THREAD

**Issue by BeLink13** [shukari/TBMod#29]
Ein Modul mit einem Modus, der direkten Tod ausschließt, sondern wie ein normaler Spieler bei tödlichen Schaden verhält. (Stirbt nicht direkt und ist wiederbelebbar, hält mehr Schaden aus)

**Comment by shukari** [comment]
https://github.com/acemod/ACE3/blob/e5a15d200f44df5fccc0bc5575d18d80b35538dd/addons/medical/functions/fnc_setUnconscious.sqf#L58-L64

remoteControlledAI auf TRUE
enableUnconsciousnessAI auf 0

Modul setzt einheiten auf:
enableUnconsciousnessAI auf 2
