### ISSUE TITLE
Sprengmeister Arsenal

### ISSUE THREAD

**Issue by mordl** [shukari/TBMod#3]
Der Sprengmeister benötigt Zugriff auf größere Rucksäcke. 
Da nur er befugt ist den Werkzeugkasten mit sich zu führen bzw. in zu benutzen,
hat er zu wenig Platz für genug Sprengladungen.

**Comment by Er1807** [comment]
In https://github.com/shukari/TBMod/commit/a65ce5d0b28a2034d533157fa31c24229a660709 wurde _gepaeck_mittel aka Kitbag zum Sprengmeister hinzugefügt.

**Comment by shukari** [comment]
Die Große Rucksäcke würde ich nur für Muniträger und AT lassen.
Der Werkzeugkasten soll eine Außnahme sein, das der mitgenommen wird, als Spezialrolle innerhalb der Gruppe.
