### ISSUE TITLE
EOS Zone [Culli Wünsche]

### ISSUE THREAD

**Issue by shukari** [shukari/TBMod#32]
- ~~keine groupSizes mehr mehr, sondern genaue Angaben (feste Anzahl) an Einheiten, Angabe dann nur noch [ANZAHL Gruppen, ANZAHL der Einheiten pro Gruppe]~~
- ~~normales zonenModul Marker sichtbar anscheined vertauscht~~
- ~~Wahrscheinlichkeit löschen, nicht erwünscht~~
- ~~markertype löschen, gibt derzeit zwischen 0-2 um Alpha zu bestimmen, dass soll gelöscht werden und Alpha auf 0.8 gesetzt werden~~
- ~~feature request: mit Spieler skalieren (zB pro Spieler Faktor einstellen zB 0.1 das ab 10 Spielern zusätzlich eine Gruppe überall rauf geht)~~
- ~~side als drop down menü~~
- ~~feature request: parachute abwurf der chopper cargo einheiten (Archilles halo parachut skript)~~

**Comment by shukari** [comment]
@Er1807 Habe alles nochmal genauer spezifiziert. Würde mich da ransetzen und das machen, wenn du aber nicht weißt wohin mit dir dann übernehme das.

**Comment by Er1807** [comment]
keine groupSizes mehr mehr, sondern genaue Angaben (feste Anzahl) an Einheiten, Angabe dann nur noch [ANZAHL Gruppen, ANZAHL der Einheiten pro Gruppe]
und
feature request: mit Spieler skalieren (zB pro Spieler Faktor einstellen zB 0.1 das ab 10 Spielern zusätzlich eine Gruppe überall rauf geht)
durch #33
