### ISSUE TITLE
Safestart als chat befehl für lvl 2

### ISSUE THREAD

**Issue by IDarky** [shukari/TBMod#34]
- Starten - GLOBAL ausführen:
	[true] call TB_fnc_safe;
        Chatbefehl: #Safe
- Beenden - GLOBAL ausführen:
	[false] call TB_fnc_safe;
        Chatbefehl: #Unsafe
@shukari

**Comment by shukari** [comment]
Genehmigt, kann umgesetzt werden.

**Comment by Er1807** [comment]
Würde vlt. als Chatbefehl #Safe on/off

**Comment by shukari** [comment]
@Er1807 genau, wie die Vanilla ChatCommands, wenn ohne Parameter `#safe` wirkt es als toggle und wenn ein Parameter kommt dann macht es das... `#safe 0/1` denke 0 und 1 wäre besser

**Comment by Er1807** [comment]
`["safe", {
    if (getPlayerUID player in (TB_lvl3 + TB_lvl2)) then 
    {
    switch (_this select 0) do {
        case "on" : {[true] remoteExec ["TB_fnc_safe"]};
        case "off": {[false] remoteExec ["TB_fnc_safe"]};
        default { systemChat "#safe on/off"; };
    };
    };
}, "all"] call CBA_fnc_registerChatCommand;`
Das wäre jetzt mein vorschlag

**Comment by shukari** [comment]
Für Code in den Comments hier immer markieren und oben die 

> <>

 anklicken ;D

**Comment by IDarky** [comment]
### Zeus Gruppe von der Karte verschwinden (Bluetrack)
- Ausblenden - LOKAL ausführen:
	(group player) setVariable ["ace_map_hideBlueForceMarker", true, true];
- (Wieder)Einblenden - LOKAL ausführen:
	(group player) setVariable ["ace_map_hideBlueForceMarker", false, true];
@shukari  das am besten  noch als Chatbefehl
