### ISSUE TITLE
customloadout beschreibung updaten

### ISSUE THREAD

**Issue by shukari** [shukari/TBMod#36]
https://github.com/shukari/TBMod/blob/b1d6b322f134fa49c7490b617f65053b9a48a8ac/TB_MAINCORE.VR/init.sqf#L1

umschreiben auf ace arsenal export und reinkopieren

**Comment by Er1807** [comment]
? Ist getUnitLoadout nicht die gleiche Funktion wie aceArsenal Export?

**Comment by shukari** [comment]
Nicht anwenderfreundliche Beschreibung derzeit 😖
