### ISSUE TITLE
Weitere Chatbefehle -> SkripteSammlung

### ISSUE THREAD

**Issue by shukari** [shukari/TBMod#37]
Alles aus der [SkripteSammlung](https://github.com/shukari/TBMod/wiki/SkripteSammlung) als Chatbefehl

Darky
> ### Zeus Gruppe von der Karte verschwinden (Bluetrack)
> * Ausblenden - LOKAL ausführen:
>   (group player) setVariable ["ace_map_hideBlueForceMarker", true, true];
> * (Wieder)Einblenden - LOKAL ausführen:
>   (group player) setVariable ["ace_map_hideBlueForceMarker", false, true];
>   @shukari  das am besten  noch als Chatbefehl

**Comment by Er1807** [comment]
Ppppppp5ppppppppppp5ppppppppppoppppppppppppp
