### ISSUE TITLE
Grenadier Arsenal

### ISSUE THREAD

**Issue by mordl** [shukari/TBMod#4]
Die Buckshot und HET Unterlaufgeschosse sollten entfernt werden.
Der Schaden ist zu gering, um eine gepanzerte Infanterie auszuschalten.
Bei der HET konnte man zwar einen Unterschied bei der Art der Explosion sehen,
jedoch ist sie untauglich, wenn sie in einem kleineren Radius nur tödlich ist, als HE.

Hat vielleicht etwas damit zu tun, dass es Bestandteil von rhs ist und ich es an Vanilla-KI getestet habe.

**Comment by shukari** [comment]
Habe Tests gemacht und die Enginewerte aus der Konfig ausgelesen, man konnte sehen das die Rounds starke Unterschiede aufweisen:
- **M397 HET** ist einfach nur böse, setzt auf und explodiert dann 2m in der Luft, wie die Sprungminen dadurch größere Splitterwirkung
- **M441 HE** ist für nur Explosion und Splitterwirkung
- **M433 HEDEP** hat mehr Sprengstoff und einen Penetrator, der leichte Sachen (Blechzaun) durchdringen kann, dadurch kann er Motoren von leichtgepanzerten Fahrzeugen kaputtmachen, weil er die äußere Panzerung durchdringen kann

Buckshot wird entfernt sowie die Vanilla 40mm.

**Comment by shukari** [comment]
HINWEIS:
HET und HEDP waren von ACE3 falsch konfiguriert bei uns demnächst gefixt
