### ISSUE TITLE
Minenkiste /Sanikiste

### ISSUE THREAD

**Issue by IDarky** [shukari/TBMod#40]
- Neue Nachschubskiste: Minen
- ~~In Medic kisten das Kochsalz durch Blut ersetzen~~

**Comment by Er1807** [comment]
Welche Minen und wie viele?

**Comment by shukari** [comment]
Vom Sprengmeister einfach paar Infanterie- paar Fahrzeugminen... von jedem 3-5... wird sowieso derzeit eher selten benutzt...
