### ISSUE TITLE
Extremes Sanisystem

### ISSUE THREAD

**Issue by Culli-TB** [shukari/TBMod#44]
Anscheinend funktioniert das extreme Sanitätersystem nicht. Habe es im Editor angewählt aber der Arzt konnte in der Mission auf unserem Server keine Endheilung vornehmen. Muss vielleicht doch noch irgendwas eingestellt werden? Desweiteren hatten wir 2-3x das Problem das nach der Heilung der Patienten kurze Zeit später der Soldat aus unerklärlichen Gründen wieder Ohnmächtig wurde.

**Comment by shukari** [comment]
Problem war das der Zeus nur Bewustlosigkeit zmgestellt hatte

**Comment by Culli-TB** [comment]
https://github.com/shukari/TBMod/blob/26a1e17dcfadbaeab3e06c5ae4fb84a5bb1804a0/addons/TBMod_main/functions/fn_extremMedicMode.sqf#L14

Das muss auskommentiert werden.

**Comment by Er1807** [comment]
@Culli-TB Nur Auskommentiert oder verändert werden? 
ace_medical_uselocation_pak = 0; // Locations PAK (Adv) - Where can the personal aid kit be used? - Anywhere = 0, Medical Vehicles = 1, Medical facility = 2, Vehicles & facility = 3, Disabled = 4
Weiß nicht ob die Werte korrekt sind, ist von 2015
