### ISSUE TITLE
Themen Arsenal

### ISSUE THREAD

**Issue by shukari** [shukari/TBMod#50]
Für Unsung und weitere ggf StarWars usw

per `isClass (configfile >> "CfgPatches" >> "<unsungPATCH>")` variabel machen damit keine statischen Arsenale die nur einmal genutzt werden

**Comment by Er1807** [comment]
Da ich mich im Arsenal System nahezu garnicht auskenne, muss du das glaube machen.

**Comment by shukari** [comment]
in 15minuten ist es gemacht... sitze gerade dran ^^

**Comment by IDarky** [comment]
wenn mir jemand das mit den Arsenalen erklärt biete ich meine hilfe gerne an @shukari

**Comment by shukari** [comment]
Hier ist die PBO:
[TBMod_arsenal.zip](https://github.com/shukari/TBMod/files/2456312/TBMod_arsenal.zip)

**Comment by IDarky** [comment]
bin dran

**Comment by IDarky** [comment]
![image](https://user-images.githubusercontent.com/42013222/46623681-b62aea00-cb2e-11e8-905c-50167667b985.png)

ich hoffe so ist das richtig einmal bitte überprüfen. Wenn ich das so schreibe bekommt der Lead diese Waffe richtig? @shukari @Er1807

**Comment by shukari** [comment]
Jop Munition muss dann nur in allgemeinArray rein oder in den dann neuen leader_munition array siehe dmr als example... träger nicht vergessen

**Comment by shukari** [comment]
Allerdings müssten beide schon im grenadier_waffen array sein

**Comment by IDarky** [comment]
ok die lrs sind schon oben in der sqf erwähnt das heißt ich muss die nicht nocheinmal reinschreiben. Was meinst du mit träger? @shukari

**Comment by IDarky** [comment]
wie mache ich jetzt einen commit?

**Comment by shukari** [comment]
@IDarky Alle antworten haste als WA Sprachnachricht, geht schneller als hier 😃
