### ISSUE TITLE
ULG-Rauch

### ISSUE THREAD

**Issue by mordl** [shukari/TBMod#9]
Habe heute ein paar Tests mit den 3-Schuss und 1-Schuss Rauchgranaten für Unterlaufgranatenwerfer gemacht. 

Dabei habe ich folgendes bemerkt:
- Es scheint drei Patterns zu geben wie sie springen (hoher, mittlerer und kleiner Sprung nach Aufschlag)
- Welches Sprungpattern auftritt scheint zufällig zu sein, jedoch scheinen bei 3-Schuss Rauch min. zwei unterschiedliche vorzukommen
- Schusswinkel, Visiereinstellung, Wind und Beschaffenheit des Bodens scheinen keinen vom Auge erkennbaren Einfluss zu haben 
(Man kann alle hintereinander abfeuern und sie fliegen trotzdem unterschiedlich nach 1. Aufschlag)
- Rauchzeit ist mit etwa 60sek bei allen gleich  (Auch normale Rauchgranaten zum Werfen)
- 3-Schuss scheinen programmiert zu sein um eine Rauchlinie zu bilden,
jedoch fliegt meistens eine ein Stück zu weit zur Seite. Führt bei schlechtem Windeinfluss zu einer Lücke bei der Rauchwand

Mein Problem:
Ich würde gerne die 3-Schuss ULG Rauchgranaten (weiß) für das Arsenal vorschlagen, da sie fürs Vorrücken auf Ziele über offene Flächen besser geeignet wären. Aber durch das zufällige Sprungpattern ist es schwer für den Grenadier den genauen Aufschlagspunkt der Rauchwand zu bestimmen (Betrifft auch 1-Schuss Rauchgranaten). Zudem müsste er von der Seite schießen, damit die Rauchwand nicht am Ende in den Laufweg der Truppen eingreift.

So gesehen kann man die ULG-Rauchgranaten nich für gezieltes Einrauchen auf Distanz verwenden, da der Rauchpunkt nicht berechenbar genug ist.
Man kann höchstens den Wind beachten und dann direkt unter die Füße schießen.

Gibt es einen Weg das ohne zu großen Aufwand anzupassen?

Gruß mordl

**Comment by shukari** [comment]
Man kann das Deflecting Verhalten anpassen, also die Projectile so verändern, dass sie nicht weiterfliegen.
Werde damit mal rum experimentieren.

**Comment by shukari** [comment]
Ergebnis:
- man kann nicht das deflecting abändern, aber die simulation
- mit `simulation = "shotSmoke";` schlagen die ein wie 40mm HE wenn du sie zudicht in den Boden feuerst... damit 100% genau dann, hat aber irgendwelche nachteile... sound usw
- wenn wir das integrieren wäre das ne neue Munition die mehr wiegen würde wegen der extrem verstärkten wirkweise

**Comment by shukari** [comment]
Sollte wohl mal die `timeToLive` vergrößern, da hier steht mind. 90sek -> http://www.inetres.com/gp/military/infantry/grenade/40mm_ammo.html#M676

**Comment by shukari** [comment]
- es gibt jetzt precise/AIM 40mm Smokes.
- man erkennt sie am A hinter dem Namen... zB M714A, sie bleiben da wo sie einschlagen.
- es gibt es 3-Schuss White AIM Smokes.
- alle precise/AIM Smokes halten doppelt solange und wiegen auch 3 mal soviel

Enthalten in: eb15ffa03f63734b3268d25ef6ebf231b64d1b0b
